name: tests

on:
  pull_request:
    branches:
      - "14.0*"
  push:
    branches:
      - "14.0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docker image
        run: |
        cd _docker
        mkdir -p  odoo/addons odoo/external-src data songs
        git clone git@github.com:odoo/odoo.git -b 14.0 --single-branch --depth 1 odoo/src
        git clone git@github.com:oca/server-tools -b 14.0  --single-branch --depth 1 odoo/external-src/server-tools
        docker build .
